### PR TITLE
Juliet2

### PR DESCRIPTION
**Pull request by jblss888**

### CODE REVIEW

**Comment by jblss888** [comment]
I triple checked. It just didn't like the test case from the fixtures/trucks.yml. the string "MyString" can't be parsed by JSON

**Comment by karent2222** [comment]
approved.

**Review by karent2222 — APPROVED** [review]
Works as expected

**Comment by jfelici4** [comment]
Saw the functionality in class. Approved

**Review by jfelici4 — APPROVED** [review]

**Pull request merged**
