### PR TITLE
Restriction_Modifications

### PR DESCRIPTION
**Pull request by mrayne483**
Applied restrictions for all pages related to making a new trick, editing an existing truck, showing either one or all trucks, and for deleting a truck.

### CODE REVIEW

**Comment by jfelici4** [comment]
I approve of this but we still need to go just one step further for optimal security. All this does is hide the buttons from the user if they are not logged in. But if a malicious user or robot sends a form saying to delete truck 23 to our server, then there is no checking to see if the user is logged in, it will immediately process the request like they are a logged in user. Hiding the elements from the user is important as well, but we need to also add additional checks on the backend side.

**Review by ArturoVal — APPROVED** [review]
Checked out your branch and it's working well. Agree there's some things we need to improve on, for example if you're not logged on, if you try to open a truck on the home page you can't view the information that should be publicly available.

**Comment by jblss888** [comment]
-I did notice that it won't automatically log me out, even when I shut down the server.

**Review by mrayne483 — COMMENTED** [review]
Cleaned up the display of the trucks table when not logged in, and added before_action method to turcks controller to direct routes if not logged in

**Pull request merged**
