### PR TITLE
User Location

### PR DESCRIPTION
**Pull request by ArturoVal**
Added "pan" button that will ask user to share location and then center on location.

### CODE REVIEW

**Comment by ArturoVal** [comment]
Remember to allow location access on your browser for the site. Also be aware where you are connected. When I was connected to the secure wifi on campus it kept showing my location a few blocks away. When I switched to the guest wifi my location was spot on.

**Comment by jfelici4** [comment]
Yeah the accuracy is one of the reasons why we prefer to have things scheduled. Worked for me and approved.

**Review by jfelici4 — APPROVED** [review]

**Comment by karent2222** [comment]
Approved changes

**Comment by ArturoVal** [comment]
Will merge since you both approved.

**Pull request merged**
